--------------------------------------------------------
--  파일이 생성됨 - 토요일-12월-20-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NJW_BOARD_SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."NJW_BOARD_SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NJW_CART_SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."NJW_CART_SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NJW_MEMBER_SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."NJW_MEMBER_SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NJW_PRODUCT_SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."NJW_PRODUCT_SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NJW_REMEMBER_ME_SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."NJW_REMEMBER_ME_SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NJW_SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."NJW_SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SCAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."SCAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##DBEXAM"."SEQ_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."BOARD" 
   (	"NUM" NUMBER(*,0), 
	"ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(10 BYTE), 
	"SUBJECT" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB, 
	"REGIST_DAY" VARCHAR2(30 BYTE), 
	"HIT" NUMBER(*,0), 
	"IP" VARCHAR2(20 BYTE), 
	"UUID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."CART" 
   (	"CART_ID" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"PRODUCT_ID" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER DEFAULT 1, 
	"PRICE" NUMBER(38,0), 
	"REG_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NJW_MEMBER
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."NJW_MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"MAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"UUID" RAW(16), 
	"NJW_MEMBER_SEQ_NUM" NUMBER, 
	"LOGTIME" DATE, 
	"UPDATETIME" DATE, 
	"ROLE" VARCHAR2(10 BYTE) DEFAULT 'USER'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."PRODUCT" 
   (	"NJW_PRODUCT_SEQ_NUM" NUMBER, 
	"ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(38,0), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"IMG" VARCHAR2(200 BYTE), 
	"DATE_" DATE, 
	"UUID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REMEMBER_ME_TOKENS
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."REMEMBER_ME_TOKENS" 
   (	"TOKEN_ID" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"TOKEN_VALUE" VARCHAR2(255 BYTE), 
	"EXPIRY_DATE" DATE, 
	"IP_ADDRESS" VARCHAR2(500 BYTE), 
	"USER_AGENT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCAN_HISTORY
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."SCAN_HISTORY" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"LOGTIME" DATE, 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"SCAN_DATE" DATE DEFAULT SYSDATE, 
	"MALICIOUS" NUMBER DEFAULT 0, 
	"SUSPICIOUS" NUMBER DEFAULT 0, 
	"UNDETECTED" NUMBER DEFAULT 0, 
	"HARMLESS" NUMBER DEFAULT 0, 
	"TOTAL_SCANS" NUMBER DEFAULT 0, 
	"RESULT_STATUS" VARCHAR2(50 BYTE), 
	"UUID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##DBEXAM.BOARD
SET DEFINE OFF;
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (1,'admin','노정원','hello','25/12/20',0,'0:0:0:0:0:0:0:1','4BD0D3090673479793F8874AE8E36AF8');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (2,'admin','노정원','wdwdad','25/12/20',0,'0:0:0:0:0:0:0:1','794E0D2399E048478D1FF2EF2727A495');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (3,'admin','노정원','sqS','25/12/20',0,'0:0:0:0:0:0:0:1','7035AF8E49E24F068507CA6440DFA2FC');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (4,'admin','노정원','awdwdawd','25/12/20',0,'0:0:0:0:0:0:0:1','C8C7371F6A3B48F9ACF5AB1F3B798210');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (5,'admin','노정원','1','25/12/20',0,'0:0:0:0:0:0:0:1','4E2FA364AB6049A0B2FB0595491430B1');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (6,'admin','노정원','1','25/12/20',0,'0:0:0:0:0:0:0:1','1A5DAD63C8B941C0AA008CFDF2A396F8');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (14,'admin','노정원','adwdawd','25/12/20',2,'0:0:0:0:0:0:0:1','9D1C726BCA754AE487F5C6C09DE38A8D');
Insert into C##DBEXAM.BOARD (NUM,ID,NAME,SUBJECT,REGIST_DAY,HIT,IP,UUID) values (12,'1','1','바보','25/12/20',3,null,'1B5906F9E6FE4819824D73FC1DCD6C26');
REM INSERTING into C##DBEXAM.CART
SET DEFINE OFF;
REM INSERTING into C##DBEXAM.NJW_MEMBER
SET DEFINE OFF;
Insert into C##DBEXAM.NJW_MEMBER (ID,PASSWORD,NAME,MAIL,PHONE,UUID,NJW_MEMBER_SEQ_NUM,LOGTIME,UPDATETIME,ROLE) values ('oo','$2a$10$BEzFr5JkXl1dh12nT1Oe9ejJo8QJ0flk4AcJlZ5UyTaer00Q4NOKq','123','22@gmail.com','010-4444-3333','57D4670B8783422D92DC589568B8A454',1,to_date('25/12/20','RR/MM/DD'),to_date('25/12/20','RR/MM/DD'),'USER');
Insert into C##DBEXAM.NJW_MEMBER (ID,PASSWORD,NAME,MAIL,PHONE,UUID,NJW_MEMBER_SEQ_NUM,LOGTIME,UPDATETIME,ROLE) values ('555','$2a$10$pRJvGWcKaPU3R3mAmLpP9.gPf4wvVdS3XITRiiVrq6DHXGpfa50vC','5','5@5.5','5-5-5','6CB2CE0C318C46ADB39BE62BBC4C2C84',2,to_date('25/12/20','RR/MM/DD'),to_date('25/12/20','RR/MM/DD'),'USER');
Insert into C##DBEXAM.NJW_MEMBER (ID,PASSWORD,NAME,MAIL,PHONE,UUID,NJW_MEMBER_SEQ_NUM,LOGTIME,UPDATETIME,ROLE) values ('5','$2a$10$ovlKCsFDrfXu8RxisT8De.2OmB5Vm3MMG.n3.IktjWuM6ZGeNHK9q','5','6666@6.6','3454-234234-2342342','8AFF674B06FE446AAD20AEAFA0B470FC',3,to_date('25/12/20','RR/MM/DD'),to_date('25/12/20','RR/MM/DD'),'USER');
Insert into C##DBEXAM.NJW_MEMBER (ID,PASSWORD,NAME,MAIL,PHONE,UUID,NJW_MEMBER_SEQ_NUM,LOGTIME,UPDATETIME,ROLE) values ('admin','$2a$10$oM6y9Tg8sml28r.4GcwzXub7k78Co0mQjSz0ZlMUN5xX8iu6.Goq.','노정원','admin@admin.com','010-0000-000','6256A63EC7FB4330AFB12DA75C2610D9',30,to_date('25/12/19','RR/MM/DD'),to_date('25/12/20','RR/MM/DD'),'ADMIN');
Insert into C##DBEXAM.NJW_MEMBER (ID,PASSWORD,NAME,MAIL,PHONE,UUID,NJW_MEMBER_SEQ_NUM,LOGTIME,UPDATETIME,ROLE) values ('1','$2a$10$6/9UuTptfjAarZZqFeW3eu.yV8nL5wDS//S751LWJ934DZI6GaPBS','1','1@1.1','1-1-1','06ABA95F4EA042F88DD9ED814D264778',4,to_date('25/12/20','RR/MM/DD'),to_date('25/12/20','RR/MM/DD'),'USER');
REM INSERTING into C##DBEXAM.PRODUCT
SET DEFINE OFF;
Insert into C##DBEXAM.PRODUCT (NJW_PRODUCT_SEQ_NUM,ID,NAME,PRICE,CATEGORY,DESCRIPTION,IMG,DATE_,UUID) values (3,'P111','111',111,'111','111','스크린샷(1)3.png',to_date('25/12/20','RR/MM/DD'),'2FCC2FA563C74E528AE93FC6DD8F7A46');
Insert into C##DBEXAM.PRODUCT (NJW_PRODUCT_SEQ_NUM,ID,NAME,PRICE,CATEGORY,DESCRIPTION,IMG,DATE_,UUID) values (4,'P222','222',222,'222','222','스크린샷(8).png',to_date('25/12/20','RR/MM/DD'),'3F3DF0DF2B784953A1745FB93E7DA8AD');
Insert into C##DBEXAM.PRODUCT (NJW_PRODUCT_SEQ_NUM,ID,NAME,PRICE,CATEGORY,DESCRIPTION,IMG,DATE_,UUID) values (5,'P333','333',333,'333','333','스크린샷(12)1.png',to_date('25/12/20','RR/MM/DD'),'538E3C0BC7B1496B9FF4CC3246CFAD99');
REM INSERTING into C##DBEXAM.REMEMBER_ME_TOKENS
SET DEFINE OFF;
Insert into C##DBEXAM.REMEMBER_ME_TOKENS (TOKEN_ID,USER_ID,TOKEN_VALUE,EXPIRY_DATE,IP_ADDRESS,USER_AGENT) values (20,'5','c19abf16-99bc-4fac-aa39-dd0d80e264c0',to_date('26/01/18','RR/MM/DD'),'0:0:0:0:0:0:0:1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36');
Insert into C##DBEXAM.REMEMBER_ME_TOKENS (TOKEN_ID,USER_ID,TOKEN_VALUE,EXPIRY_DATE,IP_ADDRESS,USER_AGENT) values (13,'admin','ca10fc7b-5a70-4a26-8164-106df39e0d95',to_date('26/01/19','RR/MM/DD'),'0:0:0:0:0:0:0:1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36');
REM INSERTING into C##DBEXAM.SCAN_HISTORY
SET DEFINE OFF;
Insert into C##DBEXAM.SCAN_HISTORY (NUM,ID,LOGTIME,FILE_NAME,SCAN_DATE,MALICIOUS,SUSPICIOUS,UNDETECTED,HARMLESS,TOTAL_SCANS,RESULT_STATUS,UUID) values (4,'admin',to_date('25/12/20','RR/MM/DD'),'스크린샷(1).png',to_date('25/12/20','RR/MM/DD'),0,0,0,61,61,'안전','D0C1DB6D559C48DE9EABB50C26FB978D');
--------------------------------------------------------
--  Constraints for Table SCAN_HISTORY
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."SCAN_HISTORY" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."SCAN_HISTORY" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DBEXAM"."SCAN_HISTORY" ADD UNIQUE ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."CART" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."CART" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."CART" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."CART" ADD PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."BOARD" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."BOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."BOARD" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."BOARD" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."BOARD" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DBEXAM"."BOARD" ADD UNIQUE ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("DATE_" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."PRODUCT" ADD PRIMARY KEY ("NJW_PRODUCT_SEQ_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DBEXAM"."PRODUCT" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DBEXAM"."PRODUCT" ADD UNIQUE ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NJW_MEMBER
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."NJW_MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."NJW_MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."NJW_MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."NJW_MEMBER" ADD PRIMARY KEY ("NJW_MEMBER_SEQ_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DBEXAM"."NJW_MEMBER" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REMEMBER_ME_TOKENS
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."REMEMBER_ME_TOKENS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."REMEMBER_ME_TOKENS" MODIFY ("TOKEN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."REMEMBER_ME_TOKENS" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##DBEXAM"."REMEMBER_ME_TOKENS" ADD PRIMARY KEY ("TOKEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DBEXAM"."REMEMBER_ME_TOKENS" ADD UNIQUE ("TOKEN_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."BOARD" ADD CONSTRAINT "FK_BOARD_MEMBER" FOREIGN KEY ("ID")
	  REFERENCES "C##DBEXAM"."NJW_MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "C##DBEXAM"."CART" ADD CONSTRAINT "FK_CART_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "C##DBEXAM"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##DBEXAM"."CART" ADD CONSTRAINT "FK_CART_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "C##DBEXAM"."NJW_MEMBER" ("ID") ON DELETE CASCADE ENABLE;
